name: CI - Build & Push FE Image

on:
  push:
    branches: ["demo"]

env:
  REGISTRY: reg.ospgroup.vn
  IMAGE_NAME: demok8s/bttp-fe

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Harbor (manual)
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: List files in the workspace
        run: ls -la

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}

          # Optional: latest tag hoặc v1
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1
