name: CI - Build & Push FE Image (Docker)

on:
  push:
    branches: ["demo"]

env:
  REGISTRY: reg.ospgroup.vn
  IMAGE_NAME: demok8s/bttp-fe

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean Docker system
        run: |
          docker system prune -f
          docker builder prune -f

      - name: Setup Docker Buildx
        run: |
          docker buildx create --use --name mybuilder --driver docker-container || true
          docker buildx inspect --bootstrap

      - name: Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v1 \
            .

      - name: Cleanup
        if: always()
        run: |
          docker buildx rm mybuilder || true
          docker system prune -f